In [ ]:
inputs = [1, 2, 3] # 3 node input layer
weights = [0.2, 0.8, -0.5]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

In [ ]:
inputs = [1, 2, 3, 2.5] # 4 node hidden layer
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[2]*weights[2] + bias
print(output)

In [2]:
# 3 neurons 4 inputs
inputs = [1, 2, 3, 2.5] # 4 node hidden layer

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, -0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[2]*weights1[2] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[2]*weights2[2] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[2]*weights3[2] + bias3]
print(output)


[0.8, 0.1200000000000001, 0.72]


In [ ]:
inputs = [1, 2, 3, 2.5] # 4 node hidden layer

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, -0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = [] # Output of current layer
for neuron_weights, neuron_bias in zip(weights, biases): 
    # zip combines lists into a singular list that has list as elements
    neuron_output = 0 # Output of given neuron
    for neuron_input, weight in zip(inputs, neuron_weights):
        neuron_output += neuron_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
        
print(layer_outputs)

In [4]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = np.dot(weights, inputs) + bias
print(output)

4.8


In [13]:
# Matrix Multiplication is just a dot product, but for matrices
"""Keep in mind that with Matrix multiplication you multiply row by column, and below you can see we have two 3x4   matrices so this will result in a error. 
    Need to transpose: In order to transpose we have to convert the lol or list of lists into numpy arrays"""

import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.7]
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2)) + bias2
print(layer2_outputs)

[[1.8256  4.21425 4.69065]
 [4.707   1.6828  8.0213 ]
 [2.60406 2.9477  3.35479]]


In [ ]:
"""
    The way that we initialize weights for a new neural network is to initialize them with random values between 
            the range of negative 1 and positive 1
    Tighter the range the better, so use small values, the reason why we want small values is in hopes that things      continue to trend in the range of negative 1 and positive 1.
    Usually with bigger values, as the neural network trains and gradients flow backward though the network during      backpropagation. If the weights are too large, the gradients can explode (become extremely large) or         vanish (become extremely small)
"""

"""
    1. Normalize Dataset: Basically use statistics and box-plot and min-max | stuff like that to remove outliers and to ensure the data being feed into the neural network is clean and without bias or skewing and represent the data as a whole --> kinda like the average of the data
    2. Scale the Dataset: So what this means is that some values need to be change in a way that all the values are between negative 1 and positive 1, but still maintain there meaning or true value in reference to the rest of the values in its particular category/column
"""

"""
    Weights: Tend to initialize them between the values of -0.1 to 0.1
    Bias: Tend to initialize them to 0, but not always try a small non-zero number
        Example: Let's say that for whatever reason your neurons aren't firing initially so if they go through the neural network, input multiplied by the weights, its not big enough to actually produce an output. With your bias being zero means that neuron is going to output a zero and zero multiplied by anything outputs a zero, --> so you just propageted though the entire network with all zeros
"""

In [4]:
import numpy as np
np.random.seed(0)

# Shape: [row, column]
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = 0.1 * np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        # could either be the training data (input layer) or (output from hidden layer to next layer)
    
    
layer1 = Layer_Dense(4, 5) #
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [5]:
# Activation Functions
"""
    If you use just weights and biases, you would be left with a activation function resembling a linear line of y = x, whatever the input is the output
"""